/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * URL Shortener API
 * OpenAPI spec version: 1.0.0
 */
export interface ShortenRequest {
  originalUrl: string;
}

export interface ShortenResponse {
  shortCode: string;
  shortUrl: string;
}

export interface StatsResponse {
  originalUrl: string;
  shortCode: string;
  clicks: number;
  createdAt: string;
}

