/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * URL Shortener API
 * OpenAPI spec version: 1.0.0
 */
import type {
  ShortenRequest,
  ShortenResponse,
  StatsResponse
} from './Api.schemas';

import { customInstance } from './index';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const createShortUrl = (
    shortenRequest: ShortenRequest,
 options?: SecondParameter<typeof customInstance<ShortenResponse>>,) => {
      return customInstance<ShortenResponse>(
      {url: `/api/shorten`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: shortenRequest
    },
      options);
    }
  
export const getShortUrlStats = (
    shortCode: string,
 options?: SecondParameter<typeof customInstance<StatsResponse>>,) => {
      return customInstance<StatsResponse>(
      {url: `/api/stats/${shortCode}`, method: 'GET'
    },
      options);
    }
  
export type CreateShortUrlResult = NonNullable<Awaited<ReturnType<typeof createShortUrl>>>
export type GetShortUrlStatsResult = NonNullable<Awaited<ReturnType<typeof getShortUrlStats>>>
